### ISSUE TITLE
BT 5.x overview LE Coded PHY speed table should be changed.

### ISSUE THREAD

**Issue by pirun** [steveyoon77/steveyoon77.github.io#2]
It seems that the phy speed of s=2 and s=8 should be switched.

![Untitled](https://user-images.githubusercontent.com/1169294/128636979-50f98b39-000d-494e-b966-072d92fcc476.png)

**Comment by steveyoon77** [comment]
Yes! You are right. The fault has been brought from a Silabs' white paper that published on Bluetooth SIG (:-O). Let me fix it later. Thanks!

**Comment by steveyoon77** [comment]
Fixed
